### ISSUE TITLE
Lua Error After Update 9.0.2.7-34-g67c5f9a

### ISSUE THREAD

**Issue by srhinos** [bullsei/BattleGroundEnemies#11]
```lua
2x AceLocale-3.0-6: BattleGroundEnemies: Missing entry for 'secondaryDesc'
[string "@BattleGroundEnemies\Options-Options.lua"]:1881: in function `SetupOptions'
[string "@BattleGroundEnemies\Main.lua"]:2000: in function `?'
[string "@BattleGroundEnemies\Main.lua"]:91: in function <BattleGroundEnemies\Main.lua:88>
```

Occurring since `TargetCalling_Highlight.args.Icon.name` and  `TargetCalling_Highlight.args.Icon.desc` are using i18n variables that aren't defined.

**Comment by srhinos** [comment]
Pretty sure this is an ez fix, pretty sure its supposed to be `Highlight_Color` and `Highlight_Color_Desc` respectively.

**Comment by bullsei** [comment]
Oh, that's true, i didn't think many people would use the alpha versions 🤣 i am just implementing a new stuff... I will remove this alpha from curseforge for now

**Comment by srhinos** [comment]
oh no worries, I try and use alpha versions because then I can actually report issues back to the developers and practice lua debug trying to find a solution to the problems!

The new features look really cool though, excited for them to be in a usable state!

**Comment by bullsei** [comment]
I am thinking about the target calling feature like this: every player can volunteer via an option, the grouplleader can select one volunteer to be the target caller. Then the addon will show an icon on the frame of target caller's target and play a sound or show a message (configurable) when he switches target. 

I am thinking about what would be the best place for that option, i feel like putting the target caller selection in the options panel would not be the best since it's an option you need to switch potentially every game when you play with randoms a lot, i will most likely anchor it to the enemy or ally frame (preferably enemy frame since not everyone is using ally frame) 

Do you have any thoughts on that? Feedback is always appreciated :)
